### ISSUE TITLE
HAVE_SOCKET_HEADERS

### ISSUE THREAD

**Issue by vibnwis** [siposcsaba89/socketcan-cpp#1]
Hi,
Would you mind share what the HAVE_SOCKET_HEADERS and/or the content of socketcan_cpp_export.h are for and why, please? did you experience some sort of issues when running of different OSes?

Appreciate your comment.

**Comment by siposcsaba89** [comment]
Hi, because can.h is not always available, for example on windows machines, I check it on cmake configure time, and if not present, the implementation won't use it, it will build, but will not functioning properly. That was necessary to build my application on windows. A nicer solution would be to define an interface and a corresponding socket can implementation and a dummy implementation.

socketcan_cpp_export.h is also generated on cmake configure time to control which functions and calsses will be exported when building as shared library.

I hope it helps, if you need any help building it, or have any questions, I will try to answer them.

BR,
Csaba

**Comment by vibnwis** [comment]
Very appreciate your answers. I use it on Linux system, and I have removed the socketcan_cpp_export.h, and the CAN-FD implementation, as my PC has a Classic CAN device. I have two more questions:

1)  In SocketCan::Open(), normally once  a CAN socket is created, it is normally followed by retrieving the interface name through  the ioctl(s, SIOCGIFINDEX, &ifr). However, I see your code check the frame size instead, ioctl(s, SIOCGIFMTU, &ifr), May I know what is the rationale behind that, please?

2) In Socket::write() and read(), both use CAN FD protocol. 
  i) Will it work on for the classic CAN devices? I presume you must have thought of that, did not you? the code show that it return error if it is a classic CAN device.
ii) Both read() and write() functions use CANFD_MTU, not sizeof(struct F
e.g. auto num_bytes = ::read(m_socket, &frame, CANFD_MTU);
Any reasons why you did that please?

Appreciate you comments.

**Comment by siposcsaba89** [comment]
I am not an expert on socket can interfaces, but I will try to answer your questions:
 1) Instead of using  ioctl(s, SIOCGIFINDEX, &ifr), I used if_nametoindex(ifr.ifr_name) to retreive the interface index, you can check the documentation here: https://linux.die.net/man/3/if_nametoindex, it calls ioctl inside its implementation.

2) struct canfd_frame differs from struct can_frame only in the data length(64 vs 8), whcich is the last parameter, so I assume one can safely read/write  a can_frame into a canfd_frame, you can check the difference here https://www.kernel.org/doc/Documentation/networking/can.txt. SocketCan::write checks if the mode MODE_CANFD_MTU, then set the data length accordingly. Note that  SocketMode enum values hold the can_frame size, so write will be called with the correct can_frame size, ::write(m_socket, &frame, int(m_socket_mode)). 
When calling read It is not an error if it returns a smaller value than the size argument provided. Read will only fail if we not read CAN_MTU or CANFD_MTU bytes, otherwise it will succeed. 

So I think it should work in both CAN_MTU and CANFD_MTU mode with the correct SocketMode enumeration parameter provided on construction. Default mode if the parameter is not set is MODE_CAN_MTU (CAN_MTU).
Hope it helps.

Csaba

**Comment by vibnwis** [comment]
Well explained. Thanks
